### ISSUE TITLE
Only maori words

### ISSUE THREAD

**Issue by sharmapn** [Brumbpo-Tungus/NewZealand-Wordlist#1]
Hello Brombro-Tungus,

We are working on a project that needs only Maori words.

Would it be possible to create another list which only has Maori words, removing the Places, Brands, Suburbs from this list.

Thanks,
Pankaj Sharma
Auckland University

**Comment by Brumbpo-Tungus** [comment]
Hey
That sounds like you are trying to get me to do your assignment or work for you?
Why don't you do it yourself?

**Comment by sharmapn** [comment]
I am a staff member here working on a project for the Maori people.
The project would allow users Maori people to choose Maori terms as
passwords.
But not places of names.

I know its a hard manual task - but thats why i contacted you anyway.

I thought there may be a way to seperate these words programatically -
thats why I asked.
